remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Chess Masa
description: An open-source chess project
is_project_page: "true"

show_downloads: "true"

github:
  repository_url: https://github.com/smonterola/chess-app-new
  zip_url: https://github.com/smonterola/chess-app-new/archive/refs/heads/main.zip
